#!/bin/bash

EMAIL_ADDRESS="longranger.406@gmail.com"

F_GCONF="/usr/local/etc/rsy_bak.conf"
D_CONF="/usr/local/etc/rsy_bak.d"

function email_n_fail {
	/usr/bin/mail -s "wildebeest rsy_bak failed, job: ${JOBNAME}" "${EMAIL_ADDRESS}" < $1
	exit
}

# Configs need the jobname, so set that, first.
JOBNAME=$1

# Source global and job specific configs
F_CONF=${D_CONF}/${JOBNAME}
if [ ! -f ${F_CONF} ]; then
	email_n_fail "Config does not exist: ${F_CONF}"
fi

. ${F_GCONF}
. ${F_CONF}

#TODO - haven't figured out how to turn this into a variable that doesn't
# break the command
# allow for non-standard port
#if [ $N_PORT ]; then
#	ARG_PORT="-e \"ssh -p ${N_PORT}\""
#fi

# Perform the transfer
nice rsync ${TEST} ${ARGS} ${BAK} ${DEL} -e "ssh -p ${N_PORT}" ${SPEED} ${SRC} ${DST}

# Compress the log
gzip ${F_LOG}

# Delete the new dated diff directory if it is empty
[ "$(ls -A ${D_DIFF})" ] || rmdir ${D_DIFF}
