#!/bin/bash

EMAIL_ADDRESS="shawn.dumser@gmail.com"

D_LOG="/var/log/rsy_bak"
D_LOG_ARCHIVE="/mnt/ext/backup/rsy_bak.logs"

# Perform the backups
/usr/local/bin/rsy_bak kold
/usr/local/bin/rsy_bak kold.pkg

# Move the logs to archive (/var/log is in ram or ssd)
if [ ! -d ${D_LOG_ARCHIVE} ]; then
        $STR_EML="Log archive directory does not exist:\n${D_LOG_ARCHIVE}"
        $STR_SUB="${HOSTNAME} log archive failed"
        /usr/bin/mail -s "${STR_SUB}" "${EMAIL_ADDRESS}" < ${STR_EML}
fi

mv ${D_LOG}/* ${D_LOG_ARCHIVE}
